;; Usar hard-links sem problemas com o esquema de backups do emacs
(setq backup-by-copying-when-linked t)

(load "compilation-custom.el")
(load "dired-custom.el")
(load "package-custom.el")
(load "org-mode-custom")
(load "keybindings-custom.el")
(load "full-ack-custom.el")
(load "erc-custom.el")
(load "env-vars-custom.el")
(load "lisp-parens-custom.el")
(load "highlight-changes-custom.el")
(load "rainbow-mode-custom.el")
(load "magit-custom.el")
(load "emacs-varios-custom.el")
