(require 'vim)
(vim-mode 1)
;;(setq vim:default-initial-mode 'emacs)
(vim:nmap "q" 'nil)
(add-to-list 'vim:initial-modes '(dired-mode . window))
(add-to-list 'vim:initial-modes '(ack-mode . window))
(vim:omap (kbd "C-e") 'nil)
