(load "casa/custom/macro-admin.el")
(load "casa/custom/org-casa-custom.el")
(load "casa/custom/magit-casa-custom.el")
(load "casa/custom/haskell-casa-custom.el")
(load "casa/custom/clojure-mode-casa-custom.el")
(load "casa/custom/csharp-mode-casa-custom.el")
(load "casa/custom/cider-casa-custom.el")
(load "casa/custom/sql-casa-custom.el")
(load "casa/custom/jabber-casa-custom.el")
(load "casa/custom/hacks-casa.el" 'noerror)
(load "casa/custom/eclim-autocomplete-yas-casa-custom.el")
(load "casa/custom/java-mode-casa-custom.el")
(load "casa/custom/color-theme-e-fonte-casa-custom.el")
(load "casa/custom/outros-casa-custom.el")
(load "casa/custom/python-casa-custom.el")
(load "casa/custom/projectile-casa-custom.el")
