(load "org-casa-custom.el")
(load "magit-casa-custom.el")
(load "haskell-casa-custom.el")
(load "clojure-mode-casa-custom.el")
(load "nrepl-casa-custom.el")
(load "sql-casa-custom.el")
(load "arrois-mode-casa-custom.el")
(load "jabber-casa-custom.el")
(load "hacks-casa.el" 'noerror)
(load "eclim-autocomplete-yas-casa-custom.el")
(load "java-mode-casa-custom.el")
(load "color-theme-e-fonte-casa-custom.el")
(load "outros-casa-custom.el")
