(defun timer-agua ()
  (interactive)
  (set-background-color "red")
  (message "Agua quente 5 min")
  (sleep-for 300)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "blue")
  (message "Agua fria 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "red")
  (message "Agua quente 4 min")
  (sleep-for 240)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "blue")
  (message "Agua fria 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "red")
  (message "Agua quente 3 min")
  (sleep-for 180)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "blue")
  (message "Agua fria 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "red")
  (message "Agua quente 2 min")
  (sleep-for 120)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "blue")
  (message "Agua fria 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "red")
  (message "Agua quente 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "blue")
  (message "Agua fria 1 min")
  (sleep-for 60)
  (set-background-color "white")
  (sleep-for 5)
  (set-background-color "red")
  (message "Agua quente 1 min")
  (sleep-for 60)
  (set-background-color "black"))

